module.exports = {
  extends: ['eslint:recommended'],
  parserOptions: {
    ecmaVersion: 2020,
    ecmaFeatures: {
      arrowFunctions: true,
      blockBindings: true,
      classes: true,
      defaultParams: true,
      destructuring: true,
      forOf: true,
      generators: false,
      modules: true,
      objectLiteralComputedProperties: true,
      objectLiteralDuplicateProperties: false,
      objectLiteralShorthandMethods: true,
      objectLiteralShorthandProperties: true,
      spread: true,
      superInFunctions: true,
      templateStrings: true,
    },
  },
  rules: {
    'block-scoped-var': 2,
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    camelcase: 2,
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': [2, { before: false, after: true }],
    'comma-style': [2, 'last'],
    'import/no-unresolved': 'off',
    'import/prefer-default-export': 'off',
    'init-declarations': [2, 'always'],
    'max-depth': [1, { max: 3 }],
    'max-lines': [1, { max: 150, skipBlankLines: false, skipComments: true }],
    'max-nested-callbacks': [1, { max: 4 }],
    'max-params': [1, { max: 3 }],
    'new-cap': 0,
    'no-alert': 2,
    'no-console': 1,
    'no-debugger': 2,
    'no-dupe-keys': 2,
    'no-empty': 2,
    'no-extra-semi': 2,
    'no-inline-comments': 0,
    'no-irregular-whitespace': 2,
    'no-lonely-if': 0,
    'no-mixed-spaces-and-tabs': 2,
    'no-multiple-empty-lines': 2,
    'no-new': 1,
    'no-self-compare': 2,
    'no-shadow': 0,
    'no-trailing-spaces': 2,
    'no-undef': 2,
    'no-underscore-dangle': 0,
    'no-unused-expressions': [1],
    'no-unused-vars': [1, { vars: 'local', args: 'after-used' }],
    'no-var': 2,
    'object-curly-spacing': [2, 'always'],
    'one-var': [2, 'never'],
    'padded-blocks': [2, 'never'],
    'prefer-const': 2,
    radix: 2,
    semi: [2, 'always'],
    'space-before-blocks': [2, 'always'],
    'space-before-function-paren': [
      2,
      {
        anonymous: 'never',
        named: 'never',
        asyncArrow: 'always',
      },
    ],
    'space-in-brackets': 0,
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'spaced-comment': [2, 'always'],
    strict: [2, 'never'],
    'vars-on-top': 2,
  },
};
